spring:
  kafka:
    admin:
      consumer:
        group-id: tpd-loggers
        auto-offset-reset: earliest
        bootstrap-servers: 192.168.0.107:9092
        
  tpd:
    topic-name: kingslake
    messags-per-request: 10
    